### PR TITLE
Primitive wrappers

### PR DESCRIPTION
**Pull request by Scooletz**
The primitive wrappers providing an ability to handle structs/classes wrapping primitive types. This can be handy when using strongly typed identifiers, etc.

### CODE REVIEW

**Comment by Scooletz** [comment]
Hi Kevin, Any chance to get this merge do the main repo?

**Comment by kevin-montrose** [comment]
@Scooletz haven't had a chance to review yet, I'm pretty crunched right now.  Hopefully I'll get some time to work through Jil Issues and PR this weekend.

**Comment by Scooletz** [comment]
Sounds great! Looking forward to it!
26 paź 2015 19:59 "kevin-montrose" <notifications@github.com> napisał(a):

**Comment by kamil-mrzyglod** [comment]
+1

**Comment by Scooletz** [comment]
Any update on this? I'd be great if we could ship it :)

**Comment by Scooletz** [comment]
@kevin-montrose Ping :)

**Pull request merged**
